### ISSUE TITLE
Error: Category Import

### ISSUE THREAD

**Issue by ramin83de** [akeneo/magento2-connector-community#107]
Hello there,

I'm using the Akeneo Magento 2 Community Connector on Magento 2.3.3 and running into an issue when I try to import the categories from Akeneo

When I start the import in Magento following error comes up:

[15:30:24] Start import
[15:30:24] Import ID : 5dfa46103b7e0
[15:30:24] Create temporary table
[15:30:25] completed
[15:30:26] Fill temporary table
[15:30:26] 2 line(s) found.
[15:30:27] Match code with Magento ID
[15:30:27] completed
[15:30:27] Create structure
[15:30:27] completed
[15:30:28] Create URL key
[15:30:28] Notice: Undefined index: parent_id in 
httpdocs/vendor/akeneo/module-magento2-connector-community/Job/Category.php on line 296

Any one knows the reason?

Cheers
Ramin

**Comment by Dnd-Gimix** [comment]
Hello @ramin83de ,

Thank you for your interest in the Akeneo Connector.
We have released today the fix for this issue in the latest 100.3.2 version.

Could you please upgrade your connector and try again please ?
Many thanks.

Regards,

**Comment by gregs76** [comment]
Hi,

Whewn running the composer update we get a message saying the connector is up to date to version 100.3.1. Suggests the composer source repo is not up to date?

**Comment by ramin83de** [comment]
> Hello @ramin83de ,
> 
> Thank you for your interest in the Akeneo Connector.
> We have released today the fix for this issue in the latest 100.3.2 version.
> 
> Could you please upgrade your connector and try again please ?
> Many thanks.
> 
> Regards,

Done, now it works.

Thanks!!

**Comment by ramin83de** [comment]
> Hi,
> 
> Whewn running the composer update we get a message saying the connector is up to date to version 100.3.1. Suggests the composer source repo is not up to date?

You have to change the connector version number in the composer.phar file to 100.3.2
