### ISSUE TITLE
File import

### ISSUE THREAD

**Issue by max21** [akeneo/magento2-connector-community#108]
Hi,
I notice that the mapping of file type attributes does not work well.
A file attribute in Akeneo is transform as input in Magento and when import Akeneo attributes values in Magento, the file is not downloaded in Magento media folder.

Is there a solution for that ?

Edit: as explain on https://help.akeneo.com/magento2-connector/v100/articles/what-data.html 
"As Magento 2 doesn't support the import of binary files other than images, the connector only import the relative PIM path for this attribute."

So there is no solution to import files fields between Akeneo - Magento ?

**Comment by Dnd-Gimix** [comment]
Hi @max21 ,

Thank you for your interest in Akeneo Connector.

We are currently working on the implementation of this feature in a near future, we will keep you updated on the release !

Regards,

**Comment by Dnd-Gimix** [comment]
Hello @max21  ,

We have just released in the latest **100.4.2** version of the connector support for file import : 
- Add support for file attributes import (https://help.akeneo.com/magento2-connector/v100/articles/05-configure-products.html#import-file-attributes)
- Add feature to apply default status to new products (https://help.akeneo.com/magento2-connector/v100/articles/05-configure-products.html#default-product-status)

Please check the documentation, upgrade you connector and tell us if the feature suits your needs !

Make sure after updating to also check the new "default status" feature before running your imports.

Have a good day.

Regards,
