### ISSUE TITLE
Problem with module update via composer

### ISSUE THREAD

**Issue by vasik-bukhari** [akeneo/magento2-connector-community#109]
### Environment and configuration

1. current  akeneo connector version - 100.3.0
2. magento community version 2.3.3

### Steps to reproduce

in magento's root directory run the following commands:
1. composer require akeneo/module-magento2-connector-community:100.3.2 --no-update 
2. composer update

### Expected result

Module should be update successfully and magento should work properly.

### Actual result

1. 
![image](https://user-images.githubusercontent.com/57760809/71959059-d1941180-3217-11ea-8a55-47b8da037be3.png)
2. Logs during composer update:
  - Updating guzzlehttp/guzzle (6.4.1 => 6.5.2): Downloading (100%)         
  - Updating php-http/discovery (1.7.0 => 1.7.4): Downloading (100%)         
  - Updating zendframework/zend-validator (2.12.2 => 2.13.0): Downloading (100%)         
  - Updating zendframework/zend-http (2.10.0 => 2.11.2): Downloading (100%)         
  - Updating symfony/polyfill-mbstring (v1.12.0 => v1.13.1): Downloading (100%)         
  - Updating monolog/monolog (1.25.2 => 1.25.3): Downloading (100%)         
  - Updating magento/zendframework1 (1.14.2 => 1.14.3): Downloading (100%)         
  - Updating symfony/finder (v4.3.8 => v4.4.2): Downloading (100%)         
  - Updating symfony/polyfill-ctype (v1.12.0 => v1.13.1): Downloading (100%)         
  - Updating symfony/filesystem (v4.3.8 => v4.4.2): Downloading (100%)         
  - Updating symfony/service-contracts (v1.1.8 => v2.0.1): Downloading (100%)         
  - Updating composer/ca-bundle (1.2.4 => 1.2.5): Downloading (100%)         
  - Updating zendframework/zend-db (2.10.0 => 2.11.0): Downloading (100%)         
  - Updating akeneo/module-magento2-connector-community (100.3.0 => 100.3.2): Downloading (100%)         
  - Updating magento/composer (1.5.0 => 1.5.1): Downloading (100%)         
  - Updating zendframework/zend-i18n (2.10.0 => 2.10.1): Downloading (100%)         
  - Updating zendframework/zend-log (2.11.0 => 2.12.0): Downloading (100%)         
  - Updating zendframework/zend-view (2.11.3 => 2.11.4): Downloading (100%)         
  - Updating zendframework/zend-barcode (2.7.1 => 2.8.0): Downloading (100%)         
  - Updating myclabs/deep-copy (1.9.3 => 1.9.4): Downloading (100%)         
  - Updating webmozart/assert (1.5.0 => 1.6.0): Downloading (100%)         
  - Updating phpdocumentor/reflection-docblock (4.3.2 => 4.3.4): Downloading (100%)         
  - Updating phpspec/prophecy (1.9.0 => 1.10.1): Downloading (100%)         
  - Updating amzn/amazon-pay-sdk-php (3.5.0 => 3.6.0): Downloading (100%)         
  - Updating symfony/event-dispatcher (v4.3.8 => v4.3.9): Downloading (100%)         
  - Updating symfony/options-resolver (v4.3.8 => v4.4.2): Downloading (100%)         
  - Updating symfony/polyfill-php70 (v1.12.0 => v1.13.1): Downloading (100%)         
  - Updating symfony/polyfill-php72 (v1.12.0 => v1.13.1): Downloading (100%)         
  - Updating symfony/stopwatch (v4.3.8 => v4.4.2): Downloading (100%)         
  - Updating flow/jsonpath (0.4.0 => 0.5.0): Downloading (100%)         
  - Updating fzaninotto/faker (v1.9.0 => v1.9.1): Downloading (100%)         
  - Updating mustache/mustache (v2.12.0 => v2.13.0): Downloading (100%)         
  - Updating paragonie/sodium_compat (v1.12.1 => v1.12.2): Downloading (100%)         
  - Updating symfony/polyfill-util (v1.12.0 => v1.13.1): Downloading (100%)         
  - Updating symfony/polyfill-php56 (v1.12.0 => v1.13.1): Downloading (100%)         
  - Updating symfony/config (v4.3.8 => v4.4.2): Downloading (100%)         
  - Updating symfony/dependency-injection (v4.3.8 => v4.4.2): Downloading (100%)         
  - Updating codeception/phpunit-wrapper (6.7.0 => 6.8.0): Downloading (100%)         
  - Updating symfony/dom-crawler (v4.3.8 => v4.4.2): Downloading (100%)         
  - Updating symfony/browser-kit (v4.3.8 => v4.4.2): Downloading (100%)         
  - Updating symfony/css-selector (v4.3.8 => v4.4.2): Downloading (100%)         
  - Updating symfony/yaml (v4.3.8 => v4.4.2): Downloading (100%)         
  - Updating symfony/polyfill-php54 (v1.12.0 => v1.13.1): Downloading (100%)         
  - Updating symfony/polyfill-php55 (v1.12.0 => v1.13.1): Downloading (100%)         
  - Updating phpoption/phpoption (1.5.2 => 1.7.2): Downloading (100%)         
  - Updating symfony/inflector (v4.3.8 => v5.0.2): Downloading (100%)         
  - Updating symfony/property-access (v4.3.8 => v5.0.2): Downloading (100%)         
Package container-interop/container-interop is abandoned, you should avoid using it. Use psr/container instead.
Package phpunit/phpunit-mock-objects is abandoned, you should avoid using it. No replacement was suggested.
Package zendframework/zend-captcha is abandoned, you should avoid using it. Use laminas/laminas-captcha instead.
Package zendframework/zend-code is abandoned, you should avoid using it. Use laminas/laminas-code instead.
Package zendframework/zend-config is abandoned, you should avoid using it. Use laminas/laminas-config instead.
Package zendframework/zend-console is abandoned, you should avoid using it. Use laminas/laminas-console instead.
Package zendframework/zend-crypt is abandoned, you should avoid using it. Use laminas/laminas-crypt instead.
Package zendframework/zend-di is abandoned, you should avoid using it. Use laminas/laminas-di instead.
Package zendframework/zend-diactoros is abandoned, you should avoid using it. Use laminas/laminas-diactoros instead.
Package zendframework/zend-escaper is abandoned, you should avoid using it. Use laminas/laminas-escaper instead.
Package zendframework/zend-eventmanager is abandoned, you should avoid using it. Use laminas/laminas-eventmanager instead.
Package zendframework/zend-feed is abandoned, you should avoid using it. Use laminas/laminas-feed instead.
Package zendframework/zend-filter is abandoned, you should avoid using it. Use laminas/laminas-filter instead.
Package zendframework/zend-form is abandoned, you should avoid using it. Use laminas/laminas-form instead.
Package zendframework/zend-hydrator is abandoned, you should avoid using it. Use laminas/laminas-hydrator instead.
Package zendframework/zend-inputfilter is abandoned, you should avoid using it. Use laminas/laminas-inputfilter instead.
Package zendframework/zend-json is abandoned, you should avoid using it. Use laminas/laminas-json instead.
Package zendframework/zend-loader is abandoned, you should avoid using it. Use laminas/laminas-loader instead.
Package zendframework/zend-mail is abandoned, you should avoid using it. Use laminas/laminas-mail instead.
Package zendframework/zend-math is abandoned, you should avoid using it. Use laminas/laminas-math instead.
Package zendframework/zend-mime is abandoned, you should avoid using it. Use laminas/laminas-mime instead.
Package zendframework/zend-modulemanager is abandoned, you should avoid using it. Use laminas/laminas-modulemanager instead.
Package zendframework/zend-mvc is abandoned, you should avoid using it. Use laminas/laminas-mvc instead.
Package zendframework/zend-psr7bridge is abandoned, you should avoid using it. Use laminas/laminas-psr7bridge instead.
Package zendframework/zend-serializer is abandoned, you should avoid using it. Use laminas/laminas-serializer instead.
Package zendframework/zend-server is abandoned, you should avoid using it. Use laminas/laminas-server instead.
Package zendframework/zend-servicemanager is abandoned, you should avoid using it. Use laminas/laminas-servicemanager instead.
Package zendframework/zend-session is abandoned, you should avoid using it. Use laminas/laminas-session instead.
Package zendframework/zend-soap is abandoned, you should avoid using it. Use laminas/laminas-soap instead.
Package zendframework/zend-stdlib is abandoned, you should avoid using it. Use laminas/laminas-stdlib instead.
Package zendframework/zend-text is abandoned, you should avoid using it. Use laminas/laminas-text instead.
Package zendframework/zend-uri is abandoned, you should avoid using it. Use laminas/laminas-uri instead.
Package zendframework/zend-validator is abandoned, you should avoid using it. Use laminas/laminas-validator instead.
Package zendframework/zend-http is abandoned, you should avoid using it. Use laminas/laminas-http instead.
Package zendframework/zend-db is abandoned, you should avoid using it. Use laminas/laminas-db instead.
Package zendframework/zend-i18n is abandoned, you should avoid using it. Use laminas/laminas-i18n instead.
Package zendframework/zend-log is abandoned, you should avoid using it. Use laminas/laminas-log instead.
Package zendframework/zend-view is abandoned, you should avoid using it. Use laminas/laminas-view instead.
Package zendframework/zend-barcode is abandoned, you should avoid using it. Use laminas/laminas-barcode instead.
Writing lock file
Generating autoload files

3. After this update none of the magento's commands are working in terminal.

4. Magento's frontend and backend are stuck on loading.

**Comment by Dnd-Gimix** [comment]
Hello @vasik-bukhari ,

Thank you for your interest in Akeneo Connector.

Could you please check your Magento logs to see if there is any error prompted ?
Have you flushed your Magento cache after update ?

Thank you.

Regards,

**Comment by vasik-bukhari** [comment]
I had to clear cache by deleting all the contents in var/cache folder as the magento's command 'bin/magento cache:flush' is not working. also none of the other magento commands are working.

There is nothing in logs other than cache invalidated.

here are the log files:

[debug.log](https://github.com/akeneo/magento2-connector-community/files/4034632/debug.log)
[system.log](https://github.com/akeneo/magento2-connector-community/files/4034633/system.log)
[update.log](https://github.com/akeneo/magento2-connector-community/files/4034634/update.log)

**Comment by Dnd-Gimix** [comment]
In the system.log :

_[2020-01-08 09:31:16] main.CRITICAL: The specified "/var/www/magento/generated/code/Magento/Theme/Model/ResourceModel/Theme/Collection/Proxy.php.1754" file couldn't be written. Warning!file_put_contents(/var/www/magento/generated/code/Magento/Theme/Model/ResourceModel/Theme/Collection/Proxy.php.1754): failed to open stream: No such file or directory
Class Magento\Theme\Model\ResourceModel\Theme\Collection\Proxy generation error: The requested class did not generate properly, because the 'generated' directory permission is read-only. If --- after running the 'bin/magento setup:di:compile' CLI command when the 'generated' directory permission is set to write --- the requested class did not generate properly, then you must add the generated class object to the signature of the related construct method, only. [] []_

Could you have any permission problem on your Magento files ?

**Comment by vasik-bukhari** [comment]
I have checked and updates server RAM to 16GB not the pages seems to be working but the following issue arises when I am testing my akeneo credentials 
![image](https://user-images.githubusercontent.com/57760809/71976062-6e1bdb00-323b-11ea-88b0-f309a4ae886d.png)
"Parameter "client_id" is missing or does not match any client, or secret is invalid"

I have also checked at akeneo side and the client Id and secret is available there.

![image](https://user-images.githubusercontent.com/57760809/71976228-d1a60880-323b-11ea-97e0-656ad79e1f2e.png)


Can you help me to fix this issue in magento?

**Comment by vasik-bukhari** [comment]
Hi,
This issue is resolved. It was related to bitnami server configuration. The fix is found here : https://community.bitnami.com/t/akeneo-parameter-client-id-is-missing-or-does-not-match-any-client-or-secret-is-invalid/52442/2

**Comment by Dnd-Gimix** [comment]
Hello @vasik-bukhari ,

Thank you for your update, I'll close the issue.

Regards,
