### ISSUE TITLE
Product import issue -Integrity constraint violation: 1062 Duplicate entry

### ISSUE THREAD

**Issue by vasik-bukhari** [akeneo/magento2-connector-community#111]
### Environment and configuration

1. current akeneo connector version - 100.3.0
2. magento community version 2.3.3

### Steps to reproduce

Not sure why this issue arise. But I have been importing products with respect to attribute set, because we have 400K products in akeneo, so I am importing in chunks. in configuration of connector on magento's admin page I am selecting about 10 to 15 attribute sets to be imported, import the products and then I select other 10 to 15 attribute sets in config.

After several successful imports of products I have came accross this issue once for some attribute sets.

### Expected result

1. Products should be imported successfully.
2. If there are any duplicate entries it should overwrite them in db.

### Actual result

1. 
![image](https://user-images.githubusercontent.com/57760809/72133485-8f99d580-33a7-11ea-8bb0-bb14dd3185aa.png)

[13:55:38] SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '-3.html-3' for key 'URL_REWRITE_REQUEST_PATH_STORE_ID', query was: UPDATE `url_rewrite` SET `request_path` = ?, `metadata` = ? WHERE (url_rewrite_id = '513121')

**Comment by vasik-bukhari** [comment]
Can you check this and let me know what needs to be done at magento's end to import this chuck of products successfully?

**Comment by vasik-bukhari** [comment]
I was importing 86k products from magento into akeneo but got internet connectivity issues during the import. After the connection got reset I am no more able to import products or product models from akeneo to magento 2.

![image](https://user-images.githubusercontent.com/57760809/72151700-e535a880-33ce-11ea-8fe5-d859e7dcd581.png)
![image](https://user-images.githubusercontent.com/57760809/72151792-2e85f800-33cf-11ea-86a1-8c55a0fe7cb8.png)

**Comment by Dnd-Gimix** [comment]
Hello @vasik-bukhari ,

Thank you for your interest in Akeneo Connector.

We have provided a bug fix regarding the duplicate entry errors while generating URL rewrites in the latest 100.3.4 version of the connector.

Tell us if it solved your issue ;)

Have a good day.

Regards,
