### ISSUE TITLE
Select Type Attributes created as Text Field in Magento.

### ISSUE THREAD

**Issue by maheshWebkul721** [akeneo/magento2-connector-community#12]
Akeneo Select Type Attribute saved as Text Field Type in Magento, Also attribute options do not import.   
### Environment and configuration

1. Akeneo Version:CE 3.1.17
2. Magento 2.3.2
3. 

### Steps to reproduce

1. Select Attribute Import Tab, and then start importing.
2. After successful go to Admin->Store->Product
3. Find Camera Type attribute, which is select type on akeneo. https://prnt.sc/oq06ji 
4. When you will view this attribute configuration its saved as Text Field. https://prnt.sc/oq0726 
5. If you will add this attribute on admin product page, after that you will not be able to open product page again. due to this error,
`{"0":"The \"formElement\" configuration parameter is required for the \"camera_type\" field.",` 

### Expected result

1. [Screenshots, logs or description]

### Actual result

1. [Screenshots, logs or description]

**Comment by Dnd-Gimix** [comment]
Hello @maheshWebkul721 ,

Thank you for your interest in Akeneo Connector for Magento 2 !
Could you provide us a full screenshot of your connector configuration in Magento 2 please ?

Thank you.
Regards,

**Comment by Dnd-Gimix** [comment]
Hello @maheshWebkul721 ,

Any news on this subject ?

Thank you.
Regards,

**Comment by Dnd-Gimix** [comment]
Without answers I'll close this issue.

Regards,
