### ISSUE TITLE
Attribute Group not created in Magento

### ISSUE THREAD

**Issue by vignesvaran** [akeneo/magento2-connector-community#123]
I have some Attributes Groups and Families in Akeneo. After sync attribute and family from Magento all attributes were created under "Akeneo" group only to all family. Is any solution or suggestion for this ?

**Comment by Dnd-Gimix** [comment]
Hello @vignesvaran ,

Thank you for your interest in Akeneo connector.

The behavior you described is actually a feature from the connector : https://help.akeneo.com/magento2-connector/v100/articles/where-attributes.html#where-to-find-my-attribute-groups-in-magento-2
Attribute groups are not imported anymore inside Magento 2, as they are not supposed to be representative of your e-commerce groups.

Regards,
