### ISSUE TITLE
Set a product name as the URL

### ISSUE THREAD

**Issue by oefterdal** [akeneo/magento2-connector-community#13]
Has followed the documentation for setting the product name as the URL, but still, it uses the SKU as the URL. 

### Environment and configuration
1. Version:CE 3.1.9 Slick Hare

### Steps to reproduce
Add Akeneo attribute mapping that points to the field «url_key»:
• Go to Store > Configuration > Catalog > Akeneo Connector
• Add attribute mapping
• Set Akeneo to «akeneo_product_name_field»
• Set Magento to «url_key»
• Save

### Expected result
Product name as the URL 

### Actual result
SKU as URL

**Comment by Dnd-Gimix** [comment]
Hello @oefterdal ,

Thank you for your interest in Akeneo Connector for Magento 2 !
Could you provide us a full screenshot of your connector configuration in Magento 2 please ?

Thank you.
Regards,

**Comment by oefterdal** [comment]
Thank you @Dnd-Gimix, here is a screenshot. 

<img width="2243" alt="Screenshot 2019-08-09 at 17 39 03" src="https://user-images.githubusercontent.com/1254741/62791088-bf794000-bacc-11e9-890c-eacd4b60e12a.png">

**Comment by oefterdal** [comment]
@Dnd-Gimix Do you see anything wrong in the configuration?

**Comment by oefterdal** [comment]
I have tested this on 3 different environments, I can't get it to use a custom attribute as the url_key.

**Comment by Dnd-Gimix** [comment]
Hello @oefterdal ,

I come back to you with more information : there was a typo in the connector that prevented the attribute mapping to work correctly, we have released the fix in the 100.1.1 version of the connector.

Could you please update your module and try again ?

Thank you.

Regards,

**Comment by giuseppemorelli** [comment]
Hi all,
I'm having the same issue (even in 100.1.1)
It seems the problem is in this file: `Job/Product.php` row 1140

- if you don't map url_key, you don't have problems:  url_key will be the akeneo identifier (mostly SKU)
- if you map url_key (like the example), you need a new column named `url_key-<iso code>` (ex `url_key-en_US` but the code doesn't create the column because of the variable `$isUrlKeyMapped`

Remove `$isUrlKeyMapped` and everything is ok (in both cases)

```php
/** @var bool $isUrlKeyMapped */
        $isUrlKeyMapped = $this->configHelper->isUrlKeyMapped();

        /**
         * @var string $local
         * @var array  $affected
         */
        foreach ($stores as $local => $affected) {
            if (!$isUrlKeyMapped && !$connection->tableColumnExists($tmpTable, 'url_key-' . $local)) {
                $connection->addColumn(
                    $tmpTable,
                    'url_key-' . $local,
                    [
                        'type'     => 'text',
                        'length'   => 255,
                        'default'  => '',
                        'COMMENT'  => ' ',
                        'nullable' => false,
                    ]
                );
                $connection->update($tmpTable, ['url_key-' . $local => new Expr('`url_key`')]);
            }
```

@Dnd-Gimix do you know why is there that check?

**Comment by Dnd-Gimix** [comment]
Hello @oefterdal , @giuseppemorelli,

We have provided several fixes for url_key mapping and formatting in the new 100.2.1 version of the connector.
Could you both update your connector and tell us if it solved your issues ?

Thank you.

Regards,

**Comment by oefterdal** [comment]
We gave up and went for the another integration, reported this issue the first time in May in the original repo. We also had issues with duplicate skus, but  We had to move on. Will try it again on the next project. Thank you for replying.

**Comment by Dnd-Gimix** [comment]
@oefterdal ,

Understood, sorry to hear that.
Maybe @giuseppemorelli could confirm us that the fixes provided are correcting this issue.

Have a good day !

Regards,

**Comment by Dnd-Gimix** [comment]
Hello @giuseppemorelli ,

Any news on the subject ? :)

Thank you.

Regards,

**Comment by hryvinskyi** [comment]
@Dnd-Gimix 

I have the same problem.
I fixed this problem by replacing in file Job/Product.php:

```php
/** @var array $stores */
$stores = array_merge(
    $this->storeHelper->getStores(['lang']), // en_US
    $this->storeHelper->getStores(['lang', 'channel_code']) // en_US-channel
);
```

to 

```php
/** @var array $stores */
$stores = $this->storeHelper->getStores(['lang']);
```
