### ISSUE TITLE
Configurable and variant url key generation errors

### ISSUE THREAD

**Issue by gregs76** [akeneo/magento2-connector-community#131]
The issue is with creating a url_key in magento for configurable products. The urk_key is the url value that Magento automatically creates for every product, based on the product name.

In the connector configuration you are required for both simple and configurable products to map an Akeneo attribute to the Magento url_key attribute. 

The simple configuration works fine. I have mapped the Akeneo name attribute to Magento url_key. A product with the name "Some Product Name" gets a Magento url_key populated correctly "some-product-name".

The configurable product import does not work correctly. Instead of creating the configurable product url_key as "some-product-name" it creates it as "Some Product Name"

A second related connector configurable error

I have had to change how I setup configurable variants in Akeneo by making a products name configurable at a variant level. For example Tshirt available in different colours. In theory this should be set up as Name being a common attribute and colour used to differentiate each variation. Instead I have had to create a unique name for each variation, e.g. Red Tshirt, Blue tshirt etc...

I have had to do this because when trying to import these products into Magento I was getting SQL duplicate entry error messages because the connector was trying to create url_keys for the different variations, but I think it was not including the colour variation when trying to create a url_key for each variation.

### Environment and configuration

1. 
2. 
3. 

### Steps to reproduce

1. 
2. 
3. 

### Expected result

1. [Screenshots, logs or description]

### Actual result

1. [Screenshots, logs or description]

**Comment by gregs76** [comment]
Some further investigation.

I have 7 different websites on Magento - UK, USA, DE, FR, NL, IT, ES
The error happens when trying to create a url rewrite for a product that is not available on all websites. 

The error is
21:44:31] SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'heated-glove-7-7' for key 'URL_REWRITE_REQUEST_PATH_STORE_ID', query was: UPDATE `url_rewrite` SET `request_path` = ?, `metadata` = ? WHERE (url_rewrite_id = '201159')


Loking at the url rewrites table, the Connector seems to be trying to create url rewrites for all store views, even though it has correctly only imported the product to the USA store view as that is the only website the product is mapped to.

The SQL error in the connector is referencing a url rewrite for the UK store view of a product. i.e The error is happening as it is trying to create a rewrite for a UK store view thats doesnt exist for the product.

Not sure if that is the issue but thought it was worth raising

**Comment by Dnd-Gimix** [comment]
Hello @gregs76 ,

Thank you for your interest in Akeneo Connector.

We have provided a bug fix for the configurable url-key generation when mapped to another attribute and also a fix for the duplicate entry errors while generating URL rewrites in the latest 100.3.4 version of the connector.

Tell us if it solved your issues ;)

Have a good day.

Regards,

**Comment by Dnd-Gimix** [comment]
Hello,

Without answer, I'll close this issue.

Beast regards,
