### ISSUE TITLE
Empty $products causing product_model import to fail

### ISSUE THREAD

**Issue by mhopkins-turnbull** [akeneo/magento2-connector-community#15]
Hi
I've connected M2 to my Akeneo v3.1 install and the product model import fails due to an empty $product on line 179 of Helper/Import/Product.php.  I've added a line to prevent this from failing - no idea why my $product array should be empty here :o(

`
            foreach ($types as $key => $products) {
>               if (empty($products)) continue;  /* ADDED LINE */
                /** @var string $name */
                $name = $group . '-' . $key;
                $associations[$name] = implode(',', $products);
            }
`

**Comment by Dnd-Gimix** [comment]
Hello @mhopkins-turnbull ,

We have provided a fix for this issue in the new 100.2.1 version of the connector.
Could you please update your connector and try again ?

Thank you.

Regards,

**Comment by Dnd-Gimix** [comment]
Hello @mhopkins-turnbull ,

Did you had the opportunity to test the fix provided ?

Regards

**Comment by mhopkins-turnbull** [comment]
Sorry - not yet.  I’ll get onto it and confirm if this sorts out the issue I had.

On 2 Oct 2019, at 16:21, Rémi Verrière <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello @mhopkins-turnbull<https://github.com/mhopkins-turnbull> ,

Did you had the opportunity to test the fix provided ?

Regards

**Comment by mhopkins-turnbull** [comment]
Hi - seems fixed now.  Thanks

**Comment by Dnd-Gimix** [comment]
Hello @mhopkins-turnbull ,

Thank you for your feedback, I'll close this issue.

Regards,
