### ISSUE TITLE
Forbidden error on product entity only

### ISSUE THREAD

**Issue by glo-arandazzo** [akeneo/magento2-connector-community#16]
### Environment and configuration
Magento 2.3.2 Enterprise
Akeneo 2.3.53

### Steps to reproduce
In the Magento control panel I am attempting to import products from Akeneo into Magento 2. I am successfully able to import all entity types (categories, families, attributes, etc.) except for product entities.

Additionally, I checked the API configuration and I seem to have all permissions applied for the configured user. I checked the PIM server apache access logs and I see the Guzzle request for an API token, but no subsequent call is ever made. All of the other entity types hit the api no problem after that.

For further testing, I went ahead and manually tested the API using the same credentials I have saved in Magento. I am able to make rest calls via curl without a problem.
 
### Expected result
I would expect the products to import like the rest of the entities.

### Actual result
I receive the following error:

```product
[17:47:14] Start import
[17:47:14] Import ID : 5d5d83a204368
[17:47:14] Create temporary table
[17:47:14] Forbidden```

Any help would be appreciated.

**Comment by Dnd-Gimix** [comment]
Hello @glo-arandazzo ,

Thank you for your interest in Akeneo Connector.

At first glance I also thought that it was related to API access on the Akeneo side but it doesn't seem to be the case from the result of your testing.

Could you please check on the server your Magento 2 logs, your PHP logs and your MYSQL logs ? The answer should be in there.
In addition, could you open your browser console during import and screenshot the response of the problematic request ?

Thanks.

Regards,

**Comment by glo-arandazzo** [comment]
Absolutely

Chrome HTTP console log:
`{"continue":false,"identifier":"5d5e8781444fa","status":false,"comment":"[12:16:01] Create temporary table","message":"[12:16:01] Forbidden"}`

There are no errors in NGINX.  The access log looks normal as far as I can tell.

`- [22/Aug/2019:12:17:53 +0000] "POST /index.php/admin/akeneo_connector/import/run/key/SESSID/?isAjax=true HTTP/1.1" 200 143 "/index.php/admin/akeneo_connector/import/index/key/SESSID/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36" "40.135.91.50"`

Magento debug.log

`[2019-08-22 12:15:52] report.DEBUG: cache_invalidate:  {"method":"GET","url":"/index.php/admin/akeneo_connector/import/index/key/SESSID/","invalidateInfo":{"identifier":"LOCKED_RECORD_INFO_SYSTEM_CONFIG"}} []`

Nothing in the Magento system.log

I will pull a mysql log here momentarily, but I am going to assume the problem is that there is something preventing it from creating the temp table. It works correctly with all of the other entity types (categories, families, etc.) and used to work fine with the products entity on the old CSV version of the Agency DND plugin. Were additional parameters added for the creation of the temp product table that were not present before? 

I am currently using Amazon Aurora w/ MySQL 5.6 compatibility, which is probably the culprit. I know 5.6 doesn't support JSON fields. 

If you can provide some insight I can keep digging over here.

Thank you!

**Comment by glo-arandazzo** [comment]
I am going to take back what I said earlier. It is not a MySQL issue. I am currently debugging through a bunch of code and it does appear to be API related. I will follow-up shortly.

**Comment by glo-arandazzo** [comment]
After a few hours of debugging, it appears to have been caused by our WAF (Cloudflare). Apparently the GET method with the search parameters in the command line were causing Cloudflare to eat the requests.  This didn't happen on the other entity types because they did not use the search parameters in the URL. Even more confusing is that cloudflare did not even log that they were blocked by the firewall, but that is something I will workout with them.

Hopefully this exercise helps someone else who may have run into this issue.

**Comment by Dnd-Gimix** [comment]
Glad you figured it out, thanks for the feedback !

Have a good day,

Regards,
