### ISSUE TITLE
Trouble updating Metrics Attribute from a value to a null value

### ISSUE THREAD

**Issue by cregnierjetpulp** [akeneo/magento2-connector-community#172]
### Environment and configuration
1. Akeneo 3.2 / Akeneo connector 100.4
2. PHP 7.3

### Steps to reproduce
1. Import a product with any metric attribute type value
2. Empty this value on Akeneo
3. Import the product one again

### Expected result
We expect this value to be empty (NULL) on Magento2 side.

### Actual result
The metric attribute value is set to 0 during the import. In the code the null value isn't unset and is convert into a float val (Akeneo\Connector\Job\Product.php:l.342) wgich is why we have a 0 instead.

**Comment by Dnd-Gimix** [comment]
Hi @cregnierjetpulp ,

Thank you for you interest in Akeneo Connector.

We have released a bug fix for this issue in the latest 100.4.5 version of the connector : https://github.com/akeneo/magento2-connector-community/releases/tag/v100.4.5

Could you please give it a try and tell us if it solved your issue ?
Make sure to check the release notes before updating your connector.

Many thanks.

Regards,

**Comment by Dnd-Gimix** [comment]
Hello,

Without answer, I'll close this issue.

Beast regards,
