### ISSUE TITLE
Too Many Requests error

### ISSUE THREAD

**Issue by akosglue** [akeneo/magento2-connector-community#194]
### Environment and configuration

1. MAMP, php 7.2. Magento2 2.3.4
2. akeneo 4 on hypernode
3. 

### Steps to reproduce

1. install akeneo magento2 connector for magento
2. fill in the requested data for connecting to akeneo
3. run self-test, or import an entity

### Expected result

1. self test or import should be successful, just like testing via Postman to query all channels

### Actual result

1. Too Many Requests error 
<img width="329" alt="Screenshot 2020-04-24 at 14 28 03" src="https://user-images.githubusercontent.com/17706334/80212478-d8645a00-8637-11ea-952e-ada2c8e74b06.png">
<img width="1331" alt="Screenshot 2020-04-24 at 14 23 45" src="https://user-images.githubusercontent.com/17706334/80212489-dbf7e100-8637-11ea-9b99-8702faf9dfd9.png">

**Comment by akosglue** [comment]
it seems to be server configuration error.

**Comment by Convert-Digital** [comment]
Hi @akosglue 

We are having the same issue - can you please let me know what you did to fix this or where/what the sever error was? 

Thanks

**Comment by akosglue** [comment]
Well, our hosting provider is hypernode: https://www.hypernode.com/about-us/
The setting concerns the nginx configuration: https://support.hypernode.com/en/hypernode/nginx/how-to-resolve-rate-limited-requests-429-too-many-requests
So, by applying the whitelist the problem was gone.
