### ISSUE TITLE
Recommended workflow for configurable products with attributes?

### ISSUE THREAD

**Issue by Wiseneus** [akeneo/magento2-connector-community#197]
I've got configurable products with many attributes in Akeneo that I want to get into Magento 2. By default all of the attributes are perfectly being synced to the simple child products, but nothing to the configurable product. I want to also have them on the configurable product, so customers can actually see them on the product page (since Magento lists the attributes of the configurable products, and not the ones of the simple childs).

I know I can define what attributes of configurable products are being transferred to Magento 2 in the extensions settings > Products > Configurable attribute mapping. But in that case I need to specify every single attribute one by one (and it are quite a lot), and everytime a new attribute is added it also needs to be specified there again. So that also isn't a viable option.

How can I make it so that every attribute on configurable products is transferred to Magento 2, just like it's on simple products?

**Comment by akosglue** [comment]
Have you found a workaround for this?

(does the image import work for you? see this issue: https://github.com/akeneo/magento2-connector-community/issues/196)

**Comment by joshiprashiddha** [comment]
@Wiseneus have to tried "**I know I can define what attributes of configurable products are being transferred to Magento 2 in the extensions settings > Products > Configurable attribute mapping.**", and got success.
For example, we need name in both configurable product and simple products associated with it, how does yours configuration for settings > Products > Configurable attribute mapping look like.

**Comment by vignesvaran** [comment]
@Wiseneus  If any update or workaround for this issue, could you please share here. Am also facing this issue.

**Comment by Wiseneus** [comment]
Hey all,

Sorry for keeping quite so long. But we managed to work around this by making a preference on the `\Akeneo\Connector\Job\Product::createConfigurable` function. Directly below the line `$additional = $this->serializer->unserialize($additional);`.

First I get all attributes `$extraAttributes = array_keys($connection->describeTable($tmpTable));`. Then I loop through the array and create a compatible associative array with the attribute name and inject it into $additional.
```php
foreach ($extraAttributes as $value) {
    $tempArray = [];
    $tempArray['attribute'] = $value;
    $tempArray['type'] = "simple";
    $tempArray['value'] = "";
    array_push($additional, $tempArray);
}
```
Hope this will help you out.
