### ISSUE TITLE
Related Items not mapped correctly

### ISSUE THREAD

**Issue by glo-arandazzo** [akeneo/magento2-connector-community#208]
### Related items were not being mapped from Akeneo to Magento 2

I am not sure if this was intentional or a bug, but In the file `Job/Product.php` at line 82 in the definition of `$associationTypes` the item `Link::LinkTypeRelated `points at the SUBSTITUTION related item type from Akeneo.. not the RELATED type. 

```
    protected $associationTypes = [
        Link::LINK_TYPE_RELATED   => [
            'SUBSTITUTION-products',
            'SUBSTITUTION-product_models',
        ],
        Link::LINK_TYPE_UPSELL    => [
            'UPSELL-products',
            'UPSELL-product_models',
        ],
        Link::LINK_TYPE_CROSSSELL => [
            'X_SELL-products',
            'X_SELL-product_models',
        ],
    ];
```

### Fix

```
    protected $associationTypes = [
        Link::LINK_TYPE_RELATED   => [
            'RELATED-products',
            'RELATED-product_models',
        ],
        Link::LINK_TYPE_UPSELL    => [
            'UPSELL-products',
            'UPSELL-product_models',
        ],
        Link::LINK_TYPE_CROSSSELL => [
            'X_SELL-products',
            'X_SELL-product_models',
        ],
    ];
```

Thank you!

**Comment by rikwillems** [comment]
The `SUBSTITUTION-products` and `SUBSTITUTION-products_models` columns don't exist and should indeed be `RELATED-products` and `RELATED-product_models`.

On my Macbook the capitalised column names are giving issues as well. These columns are not found as they are all lowercase in the table.

**Comment by Dnd-Gimix** [comment]
Hello @rikwillems @glo-arandazzo ,

Thank you for your interest in Akeneo Connector.
We have recently released a feature to handle mapping between Magento 2 Upsell / Related / Crossell with your association codes in Akeneo directly from the connector configuration : https://github.com/akeneo/magento2-connector-community/releases/tag/v101.2.0

This will allow you to choose the code of the association manually without rewriting the connector.
Have a good day !

Regards
