### ISSUE TITLE
Attributes not mapping

### ISSUE THREAD

**Issue by glo-arandazzo** [akeneo/magento2-connector-community#21]
### Environment and configuration
1. Magento 2.3.2 EE
2. Akeneo 2.3.53 CE

### Steps to reproduce
I have mapped two attributes from Akeneo to Magento. Upon importing, these values are both set as blank within Magento. It appears that all other data for custom attributes is mapped.

**Attributes Mapped in Magento Admin:**

<img width="678" alt="Screen Shot 2019-08-22 at 11 28 56 AM" src="https://user-images.githubusercontent.com/29925771/63527962-0ead7080-c4d0-11e9-80bb-3191c3d16d1c.png">

**Snippets from the Akeneo rest API:** 
For the title attribute
```
    "title": [
      {
        "locale": "en_US",
        "scope": null,
        "data": "Test Product Name"
      }
    ],
```

For the shipping_weight attribute:

```
    "shipping_weight": [
      {
        "locale": null,
        "scope": null,
        "data": {
          "amount": "31.0000",
          "unit": "POUND"
        }
      }
    ],
```

### Expected result
The data should be mapped

### Actual result
Both fields come up empty in Catalog -> Products. All other fields including description, short_description and custom attributes appear to be fine.

**Comment by glo-arandazzo** [comment]
I have found the issue.

File: `Job/Product.php`

Line 440
```
        $matches = $this->scopeConfig->getValue(ConfigHelper::PRODUCT_ATTRIBUTE_MAPPING);
        $matches = $this->serializer->unserialize($matches);
```
Returns an array with the keys `akeneo_attribute` and `magento_attribute`

Lines 449 through 473 it looks for an attribute called `pim_attribute`

```
       /** @var array $match */
        foreach ($matches as $match) {
            if (!isset($match['pim_attribute'], $match['magento_attribute'])) {
                continue;
            }

            /** @var string $pimAttribute */
            $pimAttribute = $match['pim_attribute'];
            /** @var string $magentoAttribute */
            $magentoAttribute = $match['magento_attribute'];

            $this->entitiesHelper->copyColumn($tmpTable, $pimAttribute, $magentoAttribute);

            /**
             * @var string $local
             * @var string $affected
             */
            foreach ($stores as $local => $affected) {
                $this->entitiesHelper->copyColumn(
                    $tmpTable,
                    $pimAttribute . '-' . $local,
                    $magentoAttribute . '-' . $local
                );
            }
        }
```
Changing both instances of `pim_attribute` to `akeneo_attribute` fixes the issue.

**Comment by glo-arandazzo** [comment]
Annnnd I was about to submit a PR for this and see that it was patched 9 hours earlier.  

It's been one of those days!

**Comment by Dnd-Gimix** [comment]
Hello @glo-arandazzo ,

Thank you for your interest in Akeneo Connector !

Sorry for the inconvenience, we indeed patched this issue yesterday from a community PR...
We appreciate your will to give the community a patch for the issue !

Wish you a better day than yesterday ;)

Regards,
