### ISSUE TITLE
Command Line Error - Request-URI Too Long in Release 100.4.7

### ISSUE THREAD

**Issue by bucto** [akeneo/magento2-connector-community#211]
In Release 100.4.7 the command line show into the import type family and products the message Error 'Request-URI Too Long'. The manual running of the steps directly into Magento / Akeneo Connector Import are running without problems.
I use the same command line before in 100.4.5 where it runs without any problems.

**Comment by Dnd-Gimix** [comment]
Hello @DaimPiek @bucto ,

Thank you for you interest and you feedback on the connector.
@DaimPiek: We are going to study you contribution for a future implementation.

We will keep you updated on when this bug fix will be available.

Many thanks.

Regards,

**Comment by Dnd-Gimix** [comment]
Hello @DaimPiek @bucto ,

We have integrated and released @DaimPiek fix in the latest 100.4.9 version of the connector.
Could you please upgrade your connector and try again ?

Many thanks.
Regards,
