### ISSUE TITLE
Command line error trying to run import

### ISSUE THREAD

**Issue by glo-arandazzo** [akeneo/magento2-connector-community#24]
### Environment and configuration
Magento 2.3.2
Akeneo Magento 2 Connector 100.1.1
PHP 7.2
MySQL 5.6

### Steps to reproduce
When I run Akeneo connector import from the command line, I receive the following error:

```
$ bin/magento akeneo_connector:import --code=family

In Developer.php line 55:

  Circular dependency: Magento\Logging\Model\Handler\Controllers depends on Magento\Logging\Model\Handler\Controllers and vice versa.

akeneo_connector:import [--code CODE]
``` 
Please note that I can run all of these jobs from the web interface without any problems. I have tried all of the different code types as well (product, family, category, etc.)

### Expected result
It should run an import as it does from the web interface.

### Actual result
```
$ bin/magento akeneo_connector:import --code=family

In Developer.php line 55:

  Circular dependency: Magento\Logging\Model\Handler\Controllers depends on Magento\Logging\Model\Handler\Controllers and vice versa.

akeneo_connector:import [--code CODE]
``` 

Any help would be appreciated! Thank you!

**Comment by Dnd-Gimix** [comment]
Hello @glo-arandazzo ,

Thank you for your interest in Akeneo Connector !

We couldn't replicate your issue on our developments environments.
Do you have any custom developments in your Magento 2 instance ? Like preferences for some classes ?

Could you take a look at the following links and check if any of those answers resolve your issue please : 

- https://magento.stackexchange.com/questions/94917/magento2-circular-depedency-when-reading-config?noredirect=1&lq=1
- https://magento.stackexchange.com/questions/124233/circular-dependency-magento-customer-model-session-depends-on-magento-customer
- https://github.com/magento/magento2/issues/762

Thank you.

Regards,

**Comment by glo-arandazzo** [comment]
Thank you - I forgot to mention - we are on Magento EE with the B2B module. We actually have a very small number of 3rd party extensions installed. I will see if I can debug any further.

**Comment by Dnd-Gimix** [comment]
Hell @glo-arandazzo ,

Do you have any additional inputs on your issue ?

Regards,

**Comment by adamrandazzo** [comment]
Hi - this can be closed

**Comment by Dnd-Gimix** [comment]
Hi @adamrandazzo ,

Thank you for your feedback, I'll close the issue.

Regards,

**Comment by gldt-arandazzo** [comment]
Honestly, I don't completely remember. This was four years and several major version releases. I believe that we may have had custom code using the Magento logging.
