### ISSUE TITLE
instalation new version 

### ISSUE THREAD

**Issue by sr-expert** [akeneo/magento2-connector-community#253]
BErrors during compilation:
        Akeneo\Connector\Console\Command\AkeneoConnectorImportCommand
                Incompatible argument type: Required type: string. Actual type: \Akeneo\Connector\Helper\Config; File: 
/home/user/data/rec/sources/releases/20200807141146/vendor/akeneo/module-magento2-connector-community/Console/Command/AkeneoConnectorImportCommand.php

Total Errors Count: 1

In Log.php line 92:

**Comment by Dnd-Gimix** [comment]
Hello @sr-expert ,

Thank you for your feedback, we are currently working on a fix.
We will keep you updated.

Regards,

**Comment by sr-expert** [comment]
@Dnd-Gimix 
merci c'est erreur de doc sur le __construct phpDoc annotation.  :)

**Comment by Dnd-Gimix** [comment]
@sr-expert , oui tout à fait, j'ai créé la branche et je pousserais le correctif en ligne demain afin de régler ce point : https://github.com/akeneo/magento2-connector-community/tree/fix/command_compilation

**Comment by Dnd-Gimix** [comment]
Hello @sr-expert ,

We have released the bug fix in the latest 100.4.13 version of the connector.
Thank you again for the feedback.

Have a good day !

Regards,
