### ISSUE TITLE
Product model filter bug -> empty configurable attribute values for one/more channel(s)

### ISSUE THREAD

**Issue by Melleschepers** [akeneo/magento2-connector-community#258]
Environment and configuration
1. "akeneo/module-magento2-connector-community" / version 100.4.7 (bug also exist in latest release)
2. Magento 2.3.4 (seems not to be relevant) 
3. Akeneo 4.0.44 (seems not to be relevant)

### Steps to reproduce
1. Use magento/akeneo with 2 channels/websites.
2. Map each website in akeneo with a channel in the akeneo connector.
3. Use an attribute with a "value per channel" (for example name)
3. Run the product_model import and the product import (for creation/update configurable products)

### Expected result
1. Unique vales of the attribute per website.

### Actual result
1. Website A has an empty value, website B has the right value.

Cause:
The update #199 has a loop on the filters (https://github.com/akeneo/magento2-connector-community/blob/cb0681068cba6f21badc6a0c5cd0aaadfe92721e/Job/ProductModel.php#L156). As a result; when having 2 channels.. it will loop for each channel through the product models. As a result the product models will add twice to the "tmp_akeneo_connector_entities_product_model" table (i think maybe because the identifier of that column is "NULL"??). So when having 1000 product models.. 2000 rows are present in the table "tmp_akeneo_connector_entities_product_model".

For example:
![image](https://user-images.githubusercontent.com/13859086/90235492-add62100-de21-11ea-980a-a928a57a432a.png)

When it processes the data from the "tmp_akeneo_connector_entities_product_model" table to the "akeneo_connector_product_model" table.. it first insert the first row....(which has a value in "name-nl_NL-storea")
and then it insert the second row (which has a NULL value in "name-nl_NL-storea")

As a result the "name attribute" value of the website/store A is empty.

Solution:
1. Removing the filter on the product model (don't know why it was introduced, I think something related to the unique metrics/units/data for a specific channel).... so maybe this solution is not a good option..
2. Make sure that when a product model is already inserted in the "tmp_akeneo_connector_entities_product_model" table, add a new column and update the record (same behavior as in the "tmp_akeneo_connector_entities_product" table).

**Comment by Dnd-Gimix** [comment]
Hello @Melleschepers ,

Thank you for your interest in Akeneo Connector and for the detailed issue.
This should be fixed in the latest 100.4.14, we have made sure to update the same record while navigating through filters in the event of multiple channels setup.

Could you please give it a try and confirm us that it is working well ?

Many thanks.

Regards,

**Comment by Melleschepers** [comment]
Hi @Dnd-Gimix,

Thanks for the hard works on this Akeneo Connector! It's helping us a lot and we are very happy with it :)
I will update to the current one (100.4.14) and let you know (but seeing the changes; I'm quite sure it will work)!

Have a nice day and keep up the good work!

**Comment by Melleschepers** [comment]
Sorry for my late reply but it's all working fine! 👍  Thanks!!
