### ISSUE TITLE
Import product overwrites each other with MySQL 8

### ISSUE THREAD

**Issue by Tantuss** [akeneo/magento2-connector-community#264]
When importing a lot of new products, the products start overwriting each other.

So you get the data in your database like this:
![image](https://user-images.githubusercontent.com/8715626/90686785-8396c000-e274-11ea-81a2-083986529147.png)

The reason:
Relaying on the query 'SHOW TABLE STATUS LIKE ...' to get the autoincrement of a table is not working in MySQL 8.

For the explanation of that, see:
https://stackoverflow.com/a/56390105

This code:
`$query = $connection->query('SHOW TABLE STATUS LIKE "' . $entityTable . '"');`

Is used at least in the following 3 locations:

https://github.com/akeneo/magento2-connector-community/blob/503f1ca48656009b82ff5e70c542a392a30389e9/Helper/Import/Product.php#L391

https://github.com/akeneo/magento2-connector-community/blob/2996d9278fd10f2ccbe510d75cef6e33270c3d91/Helper/Import/Entities.php#L425

https://github.com/akeneo/magento2-connector-community/blob/2996d9278fd10f2ccbe510d75cef6e33270c3d91/Helper/Import/Option.php#L139

Solutions:
1. Stop using this usage of the status tables.

2. Add a ANALYZE TABLE before getting the status table
For example add at Helper/Import/Product.php, just before line 391, add:
`$query = $connection->query('ANALYZE TABLE ' . $entityTable );`

3. Set information_schema_stats_expiry to 0

**Comment by Dnd-Gimix** [comment]
Hello @Tantuss ,

Thank you for your interest in Akeneo Connector.

We are currently working on a fix for this issue on MYSQL 8.
We will come back to you when the fix is available for a release.

Regards,

**Comment by Dnd-Gimix** [comment]
Hello @Tantuss ,

We have released a bug fix for MYSQL 8 an the auto_increment generation in the latest 100.4.16 version of the connector.
Could you please try it on your side and tell us if everything is working fine now ?

Many thanks.

Regards,

**Comment by Dnd-Gimix** [comment]
As the bug fix has been released, I'll close this issue.
