### ISSUE TITLE
 Class Akeneo\Pim\ApiClient\Search\SearchBuilderFactory does not exist

### ISSUE THREAD

**Issue by safi-rehman** [akeneo/magento2-connector-community#272]
### Environment and configuration

1. Magento 2.3.4
2.  Akeneo 3.2
3. 

### Steps to reproduce

1. Run PHP bin/magento setup:di:compile command
2. 
3. 

### Expected result

1. Compilation success and Akeneo connector should be installed successfully.

### Actual result

1. Compilation is ended with an error. 
[2020-09-28 23:13:28] main.ERROR: Class Akeneo\Pim\ApiClient\Search\SearchBuilderFactory does not exist
![compilation error](https://user-images.githubusercontent.com/67956270/94495849-7f5aac80-01fb-11eb-851c-174af3935157.png)

**Comment by arduibag** [comment]
Hi @safi-rehman, I think you tried to install the connector on PIM side.
Akeneo Connector for Magento 2 is a Magento module, so you need to install it on Magento 2.

**Comment by safi-rehman** [comment]
I installed it on Magento 2.3.4 not on PIM.

**Comment by safi-rehman** [comment]
I downloaded as zip file and tried to install it.

**Comment by Dnd-Gimix** [comment]
@safi-rehman 

You are missing the dependencies, please check the composer.json of the connector that requires the Akeneo API Client.
Can you please install it and run the se:di:co after ?

Thank you.

Regards

**Comment by safi-rehman** [comment]
After the composer installation the above mention error is resolved but I am not able to test the connection. This error is showing cURL error 60: SSL certificate problem: self signed certificate (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)
I am using this url to access my akeneo installation on my local server: https://tbgqatar.dyndns.org:100/

**Comment by safi-rehman** [comment]
Is there any way to bypass this SSL error?

**Comment by Dnd-Gimix** [comment]
Hello @safi-rehman ,

This error is related to your server / certificate setup for your Akeneo and your Magento 2 instance.
If you are using HTTPS, please configure your certificates correctly on both sides or do not use HTTPS at all.

Before using the connector, you can try to CURL the Akeneo API from your Magento 2 server to make sure that both environments can communicate correctly.

Thank you.

Regards,

**Comment by Dnd-Gimix** [comment]
As it is a server related error, I'll close this issue.
