### ISSUE TITLE
File import with uppercase attribute codes does not import files

### ISSUE THREAD

**Issue by robin-homberg** [akeneo/magento2-connector-community#274]
### Environment and configuration

1. Magento 2.3.5-p1
2. Akeneo Connector 100.4.5

### Steps to reproduce

1. Create an attribute in akeneo with an attribute code with uppercase letters
2. Assign a file to that attribute for some product
3. Enable file import in akeneo connector configuration
4. Add the attribute to akeneo connector file_attribute configuration
5. Run the product import

### Expected result

1. File should be downloaded/imported in `pub/media` directory and the path in the akeneo file attribute column should be replaced by the new path on magento2 side.
### Actual result

1. File is not downloaded, nor the path is updated

### Conclusion
 While the attribute on akeneo side has uppercase letters, and the magento2 file_attribute configuration too (where the attribute is selectable by a dropdown select), but the columns in the database table use lowercase attribute codes, it seems to be the issue that the connector is not able to match the column names using `$connection->tableColumnExists` during `importFile` of the product import.

**Comment by Dnd-Gimix** [comment]
Hello @robin-homberg ,

Thank you for you interest in Akeneo Connector and your contribution !

We are going to test your changes and integrate them into a future release of the connector.

Thanks again.

Regards,

**Comment by Dnd-Gimix** [comment]
Hello @robin-homberg ,

We have tested you contribution and it is working correctly, fixing the uppercase issue for file attributes.
We are going to integrate your changes into a future release.

We will come back to you at this moment.

Many thanks again.

Regards,

**Comment by Dnd-Gimix** [comment]
Hello @robin-homberg ,

We have released your bug fix in the latest 100.4.16 version of the connector.
Thank you again for your contribution !

Regards,

**Comment by Dnd-Gimix** [comment]
As the bug fix has been released, I'll close this issue.
