### ISSUE TITLE
Change product status

### ISSUE THREAD

**Issue by cengizcoskun** [akeneo/magento2-connector-community#276]
Hi,

Firstly, sorry my bad English.

I have got a question about product status.

I would like to change magento product status from Akeneo status attribute.

How can I do it?

**Comment by jeromecx** [comment]
Hi @cengizcoskun ,

I advise you to use a custom attribute of type simple select on the pim side, named "magento status", with this values : 

![Screenshot_2020-10-10 Attribute Status Edit](https://user-images.githubusercontent.com/19684260/95650869-b62b9f00-0ae6-11eb-9be9-790308ba4d66.png)

On Magento side, you just need to map this attribute like that : 

![Screenshot_2020-10-10 Configuration Settings Stores Magento Admin](https://user-images.githubusercontent.com/19684260/95650933-102c6480-0ae7-11eb-934b-f15f44770447.png)

Hope this can help you,

Jérôme

**Comment by cengizcoskun** [comment]
Thank you so much! I will try this soon.

**Comment by cengizcoskun** [comment]
It's worked! Thanks.

**Comment by akosglue** [comment]
This doesn't seem to work with localisable attribute. The magento store view status is not changed according to the akeneo attribute value in different locales.

**Comment by kamranmalikawan** [comment]
Hi,

We are facing same issue vis in latest version Visibility and Status is not updated in magento.

Thanks,
