### ISSUE TITLE
Import product model

### ISSUE THREAD

**Issue by cengizcoskun** [akeneo/magento2-connector-community#281]
Would you suggest the best way? for example magento settings and akeneo settings

**Comment by Dnd-Gimix** [comment]
Hello @cengizcoskun ,

Thank you for your interest in Akeneo Connector.

There is no "best way" or default settings to import product models, you'll have to define your business needs in Akeneo and make sure that the catalog structure you choose fits with the connector possibilities.

You should start by reading the documentation and make sure that your choices will be compatible with the connector : https://help.akeneo.com/magento2-connector/v100/

Have a good day !

Regards,
