### ISSUE TITLE
No results from Akeneo for the family

### ISSUE THREAD

**Issue by CelantEugenio** [akeneo/magento2-connector-community#314]
**Problem**: Can't import products because of the error `No results from Akeneo for the family:`
**Explanation**: After having imported all required elements in the Akeneo PIM (with a few CSV imports), we tried to import everything to Magento 2. Didn't use any filters, everything is not filtered. We could import everything but the product and product_models because of the error written above.

We would like to know why does this error come up since we have all products associated to the only family existent in Akeneo PIM and the Magento 2 Akeneo connector configuration does not filter out that specific family.
After a very small debugging session we saw that the **productModelApi** is called in the Product Job with a standard filter on the family. Why is that and why does that return no items?

### Environment and configuration
1. Akeneo connector v.101.0.0
2. Akeneo CE v.4.0.71
3. PHP v.7.3.21
4. Magento v.2.4.1

### Steps to reproduce
1. Create a single family
2. Create a few product_models with 1 variant in Akeneo PIM and link them to the family
3. Import in Magento2 family: OK
4. Import in Magento2 product: ERROR

### Expected result
1. Correctly import products and product models

### Actual result
1. Error **No results from Akeneo for the family: familyName**

**Comment by CelantEugenio** [comment]
Hi,
I have debugged quite deep to find the root cause of the problem I reported.

First of all I upgraded to **Akeneo Connector v101.1.0** but the problem persisted.

After that I started debugging the Akeneo api functions that provide the **Product Models**. From these I found the following:
- `vendor/akeneo/module-magento2-connector-community/Job/Product.php:381` : this is where the product models are retrieved by passing some `$filters`
- the `$filters` are returned from a call a few rows above (*line 378*) which references a function in the same file at line *2847*
- that function before doing anything else, retrieves the **family filters** (*line 2850*)
- the function `getFilters:2828` calls another homonymous function in the file `vendor/akeneo/module-magento2-connector-community/Helper/ProductFilters.php:87`
- in this last function at *line 171* a scope is added as filter:
```
$filter = [
    'search' => $search,
    'scope'  => $channel,
];
```
- removing only the *scope* filter made the error disappear

I do not understand if this is a misconfiguration on my part (I followed the guide for my first configuration) or was intended for some other purpose but doesn't work in my setting.

Just for reference, I import all my data from tailored CSVs. I use the standard `ecommerce`  Channel and just add a *category tree* and *locales*.

Would very much like an explanation of the problem I'm having and if I might be missing any steps. Thanks.

**Comment by Dnd-Gimix** [comment]
Hi @CelantEugenio ,

Thank you for you interest in Akeneo Connector.

This scope filter is made to prevent the connector from retrieving other data from unused channels by Magento 2 but obviously, you should not have to remove this parameter.

I just saw your issue and when the "No results from Akeneo for the family" appears, it sometimes means that your products are not associated to any category inside your default channel category tree. Uncategorized products will not be imported by the connector.

Could you please check this ?

Many thanks !

Regards,

**Comment by CelantEugenio** [comment]
Hi @Dnd-Gimix ,

Thank you for the quick and precise answer. I can confirm that the problem was indeed this. Manually associating the product to a category made it come up in the API call and subsequently in the Products import.

Do you have any suggestion on what to do if I need to import products without any category attached?

Thanks a lot,
Eugenio

**Comment by Dnd-Gimix** [comment]
Hello @CelantEugenio ,

For now if you want to import uncategorized products, you might want to remove with a customization the automatic scope filter added by the connector.

Thank you !
Regards,
