### ISSUE TITLE
Can't install module due to old version dependency on php-http/guzzle6-adapter

### ISSUE THREAD

**Issue by hostep** [akeneo/magento2-connector-community#332]
Hi folks

Using:
- Magento OS 2.3.5
- [`multisafepay/magento2` version 2.2.0](https://github.com/MultiSafepay/magento2) (very popular payment provider in Europe)

There is a composer dependency conflict which doesn't allow us to install `akeneo/module-magento2-connector-community` with composer.

Steps to reproduce would be to try to install both `multisafepay/magento2` and `akeneo/module-magento2-connector-community` on a Magento installation and it will fail.

```
$ composer require multisafepay/magento2 akeneo/module-magento2-connector-community
...
  Problem 1
    - multisafepay/magento2 2.2.0 requires multisafepay/magento2-core 2.1.0 -> satisfiable by multisafepay/magento2-core[2.1.0].
    - Conclusion: install akeneo/api-php-client v3.0.0
    - Conclusion: don't install akeneo/api-php-client v3.0.0|remove guzzlehttp/guzzle 6.5.5
    - Installation request for akeneo/module-magento2-connector-community ^101.1 -> satisfiable by akeneo/module-magento2-connector-community[101.1.0, 101.1.1, 101.1.2].
    - Conclusion: don't install guzzlehttp/guzzle 6.5.5
    - Installation request for multisafepay/magento2 ^2.2 -> satisfiable by multisafepay/magento2[2.2.0].
    - Can only install one of: guzzlehttp/guzzle[7.0.0, 6.5.5].
    - Can only install one of: guzzlehttp/guzzle[7.0.1, 6.5.5].
    - Can only install one of: guzzlehttp/guzzle[7.1.0, 6.5.5].
    - Can only install one of: guzzlehttp/guzzle[7.1.1, 6.5.5].
    - Can only install one of: guzzlehttp/guzzle[7.2.0, 6.5.5].
    - Installation request for guzzlehttp/guzzle (locked at 6.5.5) -> satisfiable by guzzlehttp/guzzle[6.5.5].
    - multisafepay/magento2-core 2.1.0 requires multisafepay/php-sdk ^4.0 -> satisfiable by multisafepay/php-sdk[4.0.0, 4.0.1, 4.0.2, 4.0.3].
    - multisafepay/php-sdk 4.0.3 requires psr/http-client-implementation ^1.0 -> satisfiable by guzzlehttp/guzzle[7.0.0, 7.0.1, 7.1.0, 7.1.1, 7.2.0], php-http/guzzle6-adapter[v2.0.0, v2.0.1].
    - multisafepay/php-sdk 4.0.2 requires psr/http-client-implementation ^1.0 -> satisfiable by guzzlehttp/guzzle[7.0.0, 7.0.1, 7.1.0, 7.1.1, 7.2.0], php-http/guzzle6-adapter[v2.0.0, v2.0.1].
    - multisafepay/php-sdk 4.0.1 requires psr/http-client-implementation ^1.0 -> satisfiable by guzzlehttp/guzzle[7.0.0, 7.0.1, 7.1.0, 7.1.1, 7.2.0], php-http/guzzle6-adapter[v2.0.0, v2.0.1].
    - multisafepay/php-sdk 4.0.0 requires psr/http-client-implementation ^1.0 -> satisfiable by guzzlehttp/guzzle[7.0.0, 7.0.1, 7.1.0, 7.1.1, 7.2.0], php-http/guzzle6-adapter[v2.0.0, v2.0.1].
    - php-http/guzzle6-adapter v2.0.0 requires php-http/httplug ^2.0 -> satisfiable by php-http/httplug[2.1.0, 2.2.0, v2.0.0].
    - php-http/guzzle6-adapter v2.0.1 requires php-http/httplug ^2.0 -> satisfiable by php-http/httplug[2.1.0, 2.2.0, v2.0.0].
    - Can only install one of: php-http/httplug[v1.0.0, 2.1.0].
    - Can only install one of: php-http/httplug[v1.0.0, 2.2.0].
    - Can only install one of: php-http/httplug[v2.0.0, v1.0.0].
    - akeneo/api-php-client v3.0.0 requires php-http/httplug ^1.0 -> satisfiable by php-http/httplug[v1.0.0, v1.1.0].
    - Conclusion: don't install php-http/httplug v1.1.0|install guzzlehttp/guzzle 7.0.0|install guzzlehttp/guzzle 7.0.1|install guzzlehttp/guzzle 7.1.0|install guzzlehttp/guzzle 7.1.1|install guzzlehttp/guzzle 7.2.0
```

I tried to figure out the dependency chain to see where the conflict is exactly but it's very complicated and I failed to find the exact conflict. But changing the constraint in your module of `php-http/guzzle6-adapter` to version 2 should solve it.
Your module currently has a constraint set as [`"php-http/guzzle6-adapter": "^1.1"`](https://github.com/akeneo/magento2-connector-community/blob/6c8c98e7312ebf953d655bea0a135ec0317f5146/composer.json#L11) (last version matching that constraint is [1.1.1](https://github.com/php-http/guzzle6-adapter/releases/tag/v1.1.1) which was released on 10 May 2016, so that's pretty outdated)

Would you consider adding support for version 2 of `php-http/guzzle6-adapter` and test to see if your module continues to work with it? It might just work without any needed changes but I'm not familiar with the package myself so I can't say that for certain.

**Comment by hostep** [comment]
I was just starting to take a look at creating a pull request for this but than noticed in the git history that @Dnd-Bazak is already fixing this in https://github.com/akeneo/magento2-connector-community/pull/329

Using the `dev-release/v101.2.1-dev` branch, I'm now able to install `multisafepay/magento2`, yay!

@Dnd-Bazak: is this working well for you? Any rough estimation when this will be released in a stable version? Thanks!

**Comment by Dnd-Gimix** [comment]
Hi @hostep,

Yes, we had already planned to upgrade the PHP client at the beginning of this year, I had your issue in mind and was about to warn you when it will be live :) 

Anyway, we are currently testing this new release and it should be live in a week or two, solving your issue in the process !

You can work on this branch for now if you want, but make sure to upgrade to latest version once it is released to ensure future updates.

Have a good day !
Regards

**Comment by Dnd-Gimix** [comment]
Hello @hostep ,

We have released the version 101.3.0, containing the upgrade of the Akeneo API PHP Client to 6.0, containing also the upgrade of the php-http/guzzle6-adapter dependency to 2.X.

Could you upgrade your connector and try again to confirm ?

Many thanks and have a good day !
Regards,

**Comment by hostep** [comment]
Thanks!

There were some issues at packagist we believe, because the new version didn't show up until an hour ago or so (it did in the webinterface but composer itself couldn't find the new version, very strange).
But it's too late today, so we'll give it a try tomorrow.

**Comment by hostep** [comment]
I can confirm that we can now install both modules, thanks!
