### ISSUE TITLE
Feature request: allow to edit the response from Observer

### ISSUE THREAD

**Issue by simonrl** [akeneo/magento2-connector-community#35]
Hi,

we're formatting / customizing some attributes after the import and are using the event `akeneo_connector_import_step_finish` for this.

However, when I call `$observer->getImport()->setAdditionalMessage("my message")` in my observer, the message never shows up.

I assume this is due to the response getting generated before the event:
https://github.com/akeneo/magento2-connector-community/blob/master/Job/Import.php#L447

Can we
- either create the response after the event (preferred solution)
- or add the $response object to the dispatch() method's arguments?

This way, I can tell the user what has been done, and also show exception messages if an error occured.

I'd be happy to submit a PR if you accept this feature.

Thanks
Simon

**Comment by Dnd-Gimix** [comment]
Hello @simonrl ,

Thank you for your interest in Akeneo Connector for Magento 2.

I think that creating the response after the event should do the trick !
Do not hesitate to submit us a PR on this subject ;)

Thanks again.

Regards,

**Comment by simonrl** [comment]
Here it is:

https://github.com/akeneo/magento2-connector-community/pull/49

**Comment by Dnd-Gimix** [comment]
Hello @simonrl ,

Your contribution has been added to the connector.
I'll close this issue.

Thanks again !

Regards,
