### ISSUE TITLE
Category Import: This value should be of type string.

### ISSUE THREAD

**Issue by andrew-smart** [akeneo/magento2-connector-community#354]
When importing categories, if you have a numeric category code it fails when fetching from Akeneo because "This value should be of type string". You end up with a filter like so;
{"search":{"code":[{"operator":"IN","value":[2]}]}}
Note that the 2 should be quoted.

### Environment and configuration

1. Akeneo Version: 4.0.85
2. Connector Version: 101.3.0

### Steps to reproduce

1. Set up a category with a numeric code
2. Try importing categories to Magento

**Comment by Dnd-Gimix** [comment]
Hello @andrew-smart ,

Thank you for you interest in Akeneo Connector !

We have fixed this issue in the latest version of the connector : https://github.com/akeneo/magento2-connector-community/releases/tag/v101.3.3

Could you please check that everything is now working well ?
Thank you.

Regards,
