### ISSUE TITLE
Product Job status is not resetted to Processed 

### ISSUE THREAD

**Issue by assaka** [akeneo/magento2-connector-community#526]
When running product import then status in akeneo_connector_status is not resetted to 1, but still stays on 3.

Looks like in Job/Product.php the second parameter for afterRun is true when No results are returned.

            if (empty($productModels)) {
                $this->jobExecutor->setAdditionalMessage(
                    __('No results from Akeneo for the family: %1', $this->getFamily()),
                    $this->logger
                )->afterRun(null, true);

                return;
            }

Executor/JobExecutor.php
            
`   public function afterRun($error = null, $onlyStop = null)
    {
        $this->continue = false;

        if ($onlyStop) {
            return;
        }

        if ($error) {
            $this->setJobStatus(JobInterface::JOB_ERROR);
            $this->eventManager->dispatch(
                'akeneo_connector_import_on_error',
                ['executor' => $this, 'error' => $this->getMessage()]
            );
        }

        if ($error === null && $this->currentJob->getStatus() !== JobInterface::JOB_ERROR) {
            $this->currentJob->setLastSuccessDate(date('y-m-d H:i:s'));
            $this->currentJob->setLastSuccessExecutedDate($this->currentJob->getLastExecutedDate());
            $this->setJobStatus(JobInterface::JOB_SUCCESS);
            $this->eventManager->dispatch(
                'akeneo_connector_import_on_success',
                ['executor' => $this]
            );
        } `

**Comment by akosglue** [comment]
I can confirm this, I have just run an import with the latest version: 102.3.0

Here is the log entry:

[11:58:37] Start import
[11:58:37] Import ID : 61f7ceedb2178
[11:58:37] Create temporary table
[11:58:38] completed
Path to log file : /var/log/akeneo_connector/product-import.log
No results from Akeneo for the family: 1000069

[11:58:38] Start import
[11:58:38] Import ID : 61f7ceee212c3
[11:58:38] Create temporary table
[11:58:38] completed
Path to log file : /var/log/akeneo_connector/product-import.log
No results from Akeneo for the family: 1000073


After that the import stops, but the status remains with ID 3 (processing), however it should be 1 (succes)

**Comment by akosglue** [comment]
how would you patch it @assaka ?
simply ignore that return?

for example:

    if ($onlyStop) {
        //return;
    }

**Comment by assaka** [comment]
i created a plugin to just reset the status to 1

`<?php
/**
 *
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
namespace Welhof\Main\Plugin\Akeneo\Job;
use Akeneo\Connector\Model\JobRepository;
use Akeneo\Connector\Api\Data\JobInterface;
use Magento\Framework\App\ResourceConnection;

class JobExecutor
{

	protected $resourceConnection;

	/**
	 * Description $jobRepository field
	 *
	 * @var JobRepository $jobRepository
	 */
	protected $jobRepository;

	/**
	 * JobExecutor constructor
	 *
	 * @param JobRepository $jobRepository
	 * @param ResourceConnection $resourceConnection
	 *
	 **/

	public function __construct(
		JobRepository $jobRepository,
		ResourceConnection $resourceConnection
	) {
		$this->jobRepository = $jobRepository;
		$this->resourceConnection = $resourceConnection;
	}

	/**
	 * @param \Akeneo\Connector\Executor\JobExecutor $object
	 * @param $code
	 * @param $output
	 */
	public function beforeExecute(\Akeneo\Connector\Executor\JobExecutor $object, $code, $output)
	{
		$job = $this->jobRepository->getByCode($code);
		$job->setStatus(JobInterface::JOB_SUCCESS);
		$job->setLastSuccessDate(date('y-m-d H:i:s'));
		$job->setLastSuccessExecutedDate(date('y-m-d H:i:s'));
		$job->save();
	}

}
`

**Comment by Dnd-Gimix** [comment]
Hello @assaka @akosglue ,

We have released a bug fix for this issue in the latest 102.3.2 version of the connector.
Could you please update and try again to confirm that that the job status is correctly updated to success now?

The issue was happening only if the last family had no products to be imported.

Many thanks.
Regards,

**Comment by assaka** [comment]
I have upgraded the extension to 102.3.2 and i confirm that the patch works.
Thanks!

**Comment by Dnd-Gimix** [comment]
Hello @assaka ,

Awesome, I will close this issue then!
Thank you for the feedback.

Regards,

**Comment by assaka** [comment]
I will test it once more when we have deployed to our production server.
But you can keep it closed for now :-)
