### ISSUE TITLE
Family import - attributes are not assigned to any group

### ISSUE THREAD

**Issue by MichalBroniszewski** [akeneo/magento2-connector-community#54]
## Steps to reproduce

* Import _family_ in _Magento_ admin panel
* Import _attributes_
* Add some _attributes_/_attribute_groups_ in _Akeneo PIM_ to this family
* Import _family_ again

## Expected result

After second _family_ import _attributes_ are assigned to proper _attribute groups_ in given _attribute set_.

## Actual result

On _attribute set_ edit page, _attributes_ are present, but not assigned to related _attribute group_.

## Summary
It turns out that it is necessary, to import attributes again (even if they do not change, or there is no new one) to assign them to related groups in _attribute sets_.

I think it is not a bug, but very unintuitive behaviour. _Family_ import should update all related data or at least give a hint to take some more steps (like import _attributes_ again).

**Comment by Dnd-Gimix** [comment]
Hello @MichalBroniszewski ,

Thank you for your interest in Akeneo Connector.

Indeed, it is the attribute import that is linking attributes to attribute groups.
Attributes are linked to an attribute group by their ID, so for example it is impossible to link an attribute at the "Import family step" if it is not created yet in Magento.

We will see if any hint can be added on this subject.

Regards,

**Comment by vignesvaran** [comment]
Am also  getting this issue, I have some attributes groups and Families as well in Akeneo, after sync attribute and family from Magento all attributes were created "Akeneo" group only. Please help me on this!

**Comment by Dnd-Gimix** [comment]
Hello @vignesvaran , @MichalBroniszewski 

Thank you for your interest in Akeneo connector.

The behavior you described is actually a feature from the connector : https://help.akeneo.com/magento2-connector/v100/articles/where-attributes.html#where-to-find-my-attribute-groups-in-magento-2
Attribute groups are not imported anymore inside Magento 2, as they are not supposed to be representative of your e-commerce groups.

As we are not importing attribute groups anymore, I'll close this issue.

Regards,

**Comment by vignesvaran** [comment]
@Dnd-Gimix  But am using Akeneo Connector version 100.3.2 And also I have some other setup like this, that was still working fine.
