### ISSUE TITLE
Import image attribute

### ISSUE THREAD

**Issue by oefterdal** [akeneo/magento2-connector-community#586]
# Environment and configuration

1. Akeneo Version: CE 6.0.26 Buccaneer Bunny
2. Akeneo Connector Extension Version | 103.0.0
3. Magneto 2.4.4

I have an image attribute that I want to import "main_image" in Akeneo, its not scoped in anyway but the connector gives an attribute not found error.

![image](https://user-images.githubusercontent.com/1254741/171001971-b7d70242-adf9-4b29-960b-ab795a32b4a6.png)
![image](https://user-images.githubusercontent.com/1254741/171001994-b0e8fd11-a2e2-4925-b49e-ed03463b3c65.png)

[13:37:44] Import image attributes
[13:37:44] Not Found (see https://api.akeneo.com/php-client/exception.html#not-found-exception)

**Comment by oefterdal** [comment]
![image](https://user-images.githubusercontent.com/1254741/171017603-06111d2a-5ece-4504-9ad6-48cc2baf1ce4.png)

**Comment by oefterdal** [comment]
@Dnd-Gimix Do you have a clue on how to fix this?

**Comment by oefterdal** [comment]
Note to self, use Apache not Nginx.

**Comment by jonasGossiaux** [comment]
@oefterdal I'm having the same issue, how do you fix this?

**Comment by oefterdal** [comment]
> Note to self, use Apache not Nginx.

@jonasGossiaux switched to Apache.

**Comment by oefterdal** [comment]
@jonasGossiaux  Now I get the same issue also with Apache, I am not sure what it is.

**Comment by oefterdal** [comment]
I can download the images via postman 
![image](https://user-images.githubusercontent.com/1254741/186532395-df9e6b0e-cd65-4c1f-a465-1d9fea74c2d0.png)

I don't think there is a issue with the Akeneo install but the connector.

**Comment by oefterdal** [comment]
[2022-08-24T21:49:19.043649+00:00] akeneoConnectorProductLogger.DEBUG: Info: No value found in the current batch for the attribute variant_image_4 [] []

**Comment by Dnd-Gimix** [comment]
@oefterdal : the error message "Not Found (see https://api.akeneo.com/php-client/exception.html#not-found-exception)" usually comes from the Akeneo API, when a media is missing inside your Akeneo instance and when you try to download it with the connector.
Is there any media image missing from your Akeneo instance?

**Comment by oefterdal** [comment]
The hosting provider had forgot to disable Nginx so when the server rebooted it was first to start so we got the same issue that the connector got an 404 when its using the "/download" path
