### ISSUE TITLE
Connector doesnt respect any attribute label other than default

### ISSUE THREAD

**Issue by bartoszkubicki** [akeneo/magento2-connector-community#59]
### Environment and configuration

1. Akeno connector 100.2.3
2. Magento Open Source 2.3.2

### Steps to reproduce

1. Add new attribute in akeneo
2. Add different attribute labels on different channels
3. Import attributes in akeneo connector

### Expected result

1. Attribute is imported with all labels, they should be different for different store views

### Actual result

1. Only default label is imported.

![akeneo attr labels](https://user-images.githubusercontent.com/20238194/67004883-9b943500-f0e1-11e9-9606-d575c6c11739.png)
![attr labels magento](https://user-images.githubusercontent.com/20238194/67004884-9b943500-f0e1-11e9-91db-cdbc232d2c64.png)

**Comment by Dnd-Gimix** [comment]
Hello @bartoszkubicki ,

Thank you for your interest in Akeneo Connector for Magento 2.

Can you make sure that your Akeneo locales are exactly corresponding to your Magento store locales configured under "Configuration > General > General > Locale options" please ?

Thank you.
Regards,

**Comment by bartoszkubicki** [comment]
Ok I will check it again.

**Comment by bartoszkubicki** [comment]
@Dnd-Gimix Right now I don't use this connector, so I won't verify this issue. Thank you for your help.
