### ISSUE TITLE
Akeneo Import Option paginationSize issue

### ISSUE THREAD

**Issue by padmapriya-varadhan** [akeneo/magento2-connector-community#60]
### Environment and configuration

1. Magento 2.3.2, PHP 7.2.1, MySQL 5.7.25
2. Akeneo Connector 100.1.0

### Steps to reproduce

1. Open System -> Akeneo Connector -> Import
2. Import Options
3. 10 Options imported

### Expected result

1. There are more than 10 Options available on PIM but only 10 are getting imported into our Magento System.

### Actual result

1. Only 10 options are getting imported into Magento. 

We have fixed the issue by changing the code in \app\code\Akeneo\Connector\Job\Option.php; Methods: createTable() and insertData(). Following are the changes that we did.

![image](https://user-images.githubusercontent.com/13655484/67005036-4bc46680-f0ff-11e9-80c1-522f94f4aa59.png)

![image](https://user-images.githubusercontent.com/13655484/67005077-65fe4480-f0ff-11e9-8a06-864aa22bc42c.png)

We have passed the paginationSize value to the $this->akeneoClient->getAttributeApi()->all() method. Please do fix this for us on Akeneo module.

**Comment by Dnd-Gimix** [comment]
Hello @padmapriya-varadhan ,

Thank you for you interest in Akeneo Connector.

This issue definitely seems to be related to your other issue in the Akeneo PHP API client : https://github.com/akeneo/api-php-client/issues/171

Akeneo is working to provide a fix for this issue.
Once this fix is released, we will be able to test again the connector and determine if it is necessary to apply your fix.

Thank you.

Regards,

**Comment by padmapriya-varadhan** [comment]
Hi @Dnd-Gimix, thanks for your response. Yes it surely is related to the PHP API client issue that I reported earlier.

**Comment by padmapriya-varadhan** [comment]
The paginationSize value is not passed to the "all" method similar to how it is done in categories, product and other mapping. The default pageSize is just 10. 

![image](https://user-images.githubusercontent.com/13655484/67952444-53adfb80-fc13-11e9-9ebf-eb29e558d3ee.png)

This is the createTable method. Same is the case for insertTable method too.

**Comment by Dnd-Gimix** [comment]
Same issue than : https://github.com/akeneo/magento2-connector-community/issues/70
