### ISSUE TITLE
What does this error mean?

### ISSUE THREAD

**Issue by oefterdal** [akeneo/magento2-connector-community#606]
akeneoConnectorProductLogger.DEBUG: Info: No value found in the current batch for the attribute main_image

**Comment by oefterdal** [comment]
@Dnd-Gimix  Are you able to elaborate?

**Comment by Dnd-Gimix** [comment]
@oefterdal : It means that there is no value inside the attribute "main_image" for every product currently being imported

**Comment by oefterdal** [comment]
Magically fixed it with a reboot of the server.
