### ISSUE TITLE
Attribute with no labels are imported and displayed as unknown

### ISSUE THREAD

**Issue by bartoszkubicki** [akeneo/magento2-connector-community#61]
### Environment and configuration

1. Akeno connector 100.2.3
2. Magento Open Source 2.3.2

### Steps to reproduce

1. Add new attribute in akeneo
2. Add no attribute labels
3. Import attributes in akeneo connector

### Expected result

1. Attibute is not imported and error info is shown in import log OR attribute is imported and some label is generated basing on attribute code

### Actual result

1. Attribute is imported without any notice and its displayed (in admin page, don't know how its rendered in frontend) as "Unknown"

**Comment by Dnd-Gimix** [comment]
Hello @bartoszkubicki ,

We have released a fix to prevent attributes to be inserted if no label are found in Akeneo in the version 100.2.6 of Akeneo Connector.

Before upgrading to 100.2.5 or greater, please make sure to check release notes : https://github.com/akeneo/magento2-connector-community/blob/master/CHANGELOG.md

Regards,
