### ISSUE TITLE
Return value of Akeneo\Pim\ApiClient\Client\ResourceClient::getResource() must be of the type array, null returned#0

### ISSUE THREAD

**Issue by stevelou2** [akeneo/magento2-connector-community#613]
When I have too many updated products it produces this error in console not in connector log and stopped synchronizing.
Reset the task  and run again sometimes works some times doesn't.
When I switch to another server in cluster to run, it worked.

are there any caches used on magento server?

Magento: 2.4.3-P2
Connector: 103.06

Thanks

**Comment by nghiadxvn** [comment]
I also get this issue and it stops syncing the product job. Do you know if we have any updates?

**Comment by stevelou2** [comment]
> I also get this issue and it stops syncing the product job. Do you know if we have any updates?

Try reduce the Pagination size, I set to 50 and worked, hadn't monitored the akeneo performance, but I suspect that was the cause.
Good luck
