### ISSUE TITLE
Url key doesn't work properly if attribute mapping is not set

### ISSUE THREAD

**Issue by bartoszkubicki** [akeneo/magento2-connector-community#63]
### Environment and configuration

1. Akeno connector 100.2.3
2. Magento Open Source 2.3.2

### Steps to reproduce

1. Url key with default configuration doesn't work (is imported with spaces)
2. Identifier has to be mapped as url_key in attribute configuration

### Expected result

1. Such a mapping should be defined in `config.xml` or in setup script, so without any configuration url key, as crucial magento attribute, should work out of a box 

### Actual result

1. You have to define mapping, and it is not easy to figure out, may need debbuging.

**Comment by Dnd-Gimix** [comment]
Hello @bartoszkubicki ,

Thank you for your interest in Akeneo Connector.

Could you update your connector to the latest version and tell us if you have any issues with product URL after that ?

Many thanks.

Regards,

**Comment by bartoszkubicki** [comment]
@Dnd-Gimix Right now I don't use this connector, so I won't verify this issue. Thank you for your help.
