### ISSUE TITLE
Option attribute import inserts null if no option label in akeneo

### ISSUE THREAD

**Issue by bartoszkubicki** [akeneo/magento2-connector-community#64]
### Environment and configuration

1. Akeno connector 100.2.3
2. Magento Open Source 2.3.2

### Steps to reproduce

1. Add attribute with options in akeneo 
2. Define options but randomly not fill options names in akeneo for some channels/locales
3. Import this attribute and its options

### Expected result

1. For store views, for which attribute options dont have corresponding labels nothing is inserted in db.
2. Magento loads option label from default store view, using native option labels fallback

### Actual result

1. For store views, for which attribute options dont have corresponding labels null values are inserted in db.
2. Magento load null values, instead of loading default option label
3. On frontend there are empty spaces in places where option should be rendered.

It is hard to notice it in admin panel as both null values and not exisitng values for specific store views causes just empty input for option label.

**Comment by Dnd-Gimix** [comment]
Hello @bartoszkubicki ,

We have released a fix to prevent empty options to be inserted if no label are found in Akeneo in the version 100.2.6 of Akeneo Connector.

Before upgrading to 100.2.5 or greater, please make sure to check release notes : https://github.com/akeneo/magento2-connector-community/blob/master/CHANGELOG.md

Regards,
