### ISSUE TITLE
Composer installation issue with akeneo/module-magento2-connector-community

### ISSUE THREAD

**Issue by kanapan** [akeneo/magento2-connector-community#673]
### Environment and configuration

1. PHP 8.1
2. magento 2.4.6-p3 community
3. Akeneo Connector 104.3.1

### Steps to reproduce

1. Run the command: `composer require akeneo/module-magento2-connector-community:104.3.1`
2. See the error message mentioned in the original post.

<img width="1210" alt="image" src="https://github.com/akeneo/magento2-connector-community/assets/26155436/0bc5b2d9-3cbb-4e1a-8692-5f1ccfe0b7e3">

**Comment by JacoOppermanZA** [comment]
What was the solution to this?
