### ISSUE TITLE
Family Variant import issue

### ISSUE THREAD

**Issue by padmapriya-varadhan** [akeneo/magento2-connector-community#70]
### Environment and configuration

1. Magento 2.3.1, PHP 7.2.1, MySQL 5.7.25
2. Akeneo Connector 100.2.4

### Steps to reproduce

1. Open System -> Akeneo Connector -> Import
2. Import Family Variant
3. Throwing "Found" error

### Expected result

1. Expected the Family Variants to be imported. The total number of Family variants in our system is 31 but since the default page limit set by Akeneo is only 10 and since the $paginationSize is not being passed to the all() method in createTable method, the next page is getting called for accessing the next 10 and so on. This next page call is causing the "Found" error.

### Actual result

1. 
![image](https://user-images.githubusercontent.com/13655484/67587149-ddbc1700-f770-11e9-8a34-1d4010a3aaea.png)

The Found error is an exception thrown in api-php client which is used by Connector. This happens when the next page content is getting imported. The http url of the next page is redirected to https which is causing the RedirectionException and printing the HTTP response for code 302 which is "Found"

**This issue is related to my other issue in the Akeneo PHP API client : akeneo/api-php-client#171**

**Comment by padmapriya-varadhan** [comment]
There is no option to send the paginationSize similar to categories import. 
![image](https://user-images.githubusercontent.com/13655484/67950791-522f0400-fc10-11e9-9a48-63d4f57bae77.png)

**Comment by Dnd-Gimix** [comment]
As this was related to Akeneo / server side configuration, we are closing this issue.
