### ISSUE TITLE
Option attribute useless if no labels provided in Akeneo

### ISSUE THREAD

**Issue by bartoszkubicki** [akeneo/magento2-connector-community#71]
### Environment and configuration

1. Akeno connector 100.2.3
2. Magento Open Source 2.3.2

### Steps to reproduce

1. Add attribute with options in akeneo 
2. Define options but without any labels
3. Import this attribute and its options

### Expected result

1. If we don't have any labels, attribute code is used to be inserted as default option label (or sth similar)
2. Magento loads option label from default store view, using native option labels fallback

### Actual result

1. For all store views, null values are inserted in db.
2. In admin there are empty rows, what is cirtical in case of setting multiple options without labels, as we have multiple empty rows.
3. I bet we have consequences on frontend like [#64 ](https://github.com/akeneo/magento2-connector-community/issues/64)

**Comment by Dnd-Gimix** [comment]
Hello @bartoszkubicki ,

We have released a fix to prevent empty options to be inserted if no label are found in Akeneo in the version 100.2.6 of Akeneo Connector.

Before upgrading to 100.2.5 or greater, please make sure to check release notes : https://github.com/akeneo/magento2-connector-community/blob/master/CHANGELOG.md

Regards,
