### ISSUE TITLE
Associated products issue

### ISSUE THREAD

**Issue by padmapriya-varadhan** [akeneo/magento2-connector-community#72]
### Environment and configuration

1. Magento 2.3.1, PHP 7.2.1, MySQL 5.7.25
2. Akeneo Connector 100.2.4

### Steps to reproduce

1. Associate Related, Up-sell and Cross-sell products for a product in Magento.
2. Run the imports in order.
3. When the product edit page is opened, the Related and Up-sell products remain associated to the main product but the Cross-sell association is deleted.

### Expected result
1. All 3 associations intact. 
![image](https://user-images.githubusercontent.com/13655484/68214884-43779100-0004-11ea-88e7-b261f5338d4c.png)

### Actual result

1. Cross-sell product association has been deleted after running the imports.
![image](https://user-images.githubusercontent.com/13655484/68214667-e24fbd80-0003-11ea-8d40-2afb2610e46d.png)
                 
While debugging, I found that in the following code, the associationName for up-sell and related were not present and it only had cross-sell. 

![image](https://user-images.githubusercontent.com/13655484/68216505-006aed00-0007-11ea-986b-3ff3cf5ea93d.png)

So, the existing associations were deleted and while creating the new ones, the related and up-sell associations were intact but the cross-sell association was deleted. It created cross-sell associations ONLY for products that were imported from PIM.

**Comment by Dnd-Gimix** [comment]
Hello @padmapriya-varadhan ,

We have released a fix to prevent unwanted deletion of associations in the version 100.2.6 of Akeneo Connector.

Before upgrading to 100.2.5 or greater, please make sure to check release notes : https://github.com/akeneo/magento2-connector-community/blob/master/CHANGELOG.md

Regards,
